#!/bin/bash

valgrind --suppressions=.valgrind.supp --leak-check=full --show-leak-kinds=all --track-fds=yes --trace-children=yes -s -q ./42sh "$@" 2> >(grep -v "used_suppression" | grep -v 'ERROR SUMMARY: 0 errors from 0 contexts' | grep -v "^==[0-9]*==\s*$" | grep -v "^--[0-9]*--\s*$") 63>&- 103>&- 42>&- 43>&- 44>&- 37>&- 36>&- 38>&-

# valgrind --suppressions=.valgrind.supp --leak-check=full --show-leak-kinds=all --gen-suppressions=all --track-fds=yes --trace-children=yes -s -q ./42sh
